apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T06:47:03Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1259"
  uid: 67ca4fcd-00f2-439a-8d19-b54b50489eee
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.246.143
  clusterIPs:
  - 10.97.246.143
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31831
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
